### PR TITLE
Update pen-tests.vue to add SecOps Solution

### PR DESCRIPTION
**Pull request by ashwani95**

### CODE REVIEW

**Comment by wparad** [comment]
Hey @ashwani95, thanks for adding this. I do want to call out that this has been added in the **Pen Testers** Section and the website linked does not call out the pen testing capabilities nor the pricing. Did you mean to put this somewhere else on the page?

**Comment by ashwani95** [comment]
Hi @wparad thanks for acknowledging my PR. I did meant to put it under Pen Testers section. We have done pentesting for Sprinto customers and many other direct organisations. The site is meant to talk more about our product. But we do conduct vapt too.

**Comment by wparad** [comment]
> Hi @wparad thanks for acknowledging my PR. I did meant to put it under Pen Testers section. We have done pentesting for Sprinto customers and many other direct organisations. The site is meant to talk more about our product. But we do conduct vapt too.

How does someone contact you to request a pen test, as far as I can tell from the website, there isn't actually a way to do that. Or do customers only come through sprinto?

**Comment by ashwani95** [comment]
> > Hi @wparad thanks for acknowledging my PR. I did meant to put it under Pen Testers section. We have done pentesting for Sprinto customers and many other direct organisations. The site is meant to talk more about our product. But we do conduct vapt too.
> 
> How does someone contact you to request a pen test, as far as I can tell from the website, there isn't actually a way to do that. Or do customers only come through sprinto?

Customers reach out in 3 ways:
1. Directly via Sprinto
2. There is chatbot on the website
3. There is also a contact form on the website.

Happy to share proofs of our successful Pentesting projects separately

**Comment by wparad** [comment]
Proof is not necessary. What I'm worried about is that people will get the impression that it's a valid choice and then struggle to understand the offerings or how to sign up. Right now it seems like the company is not focused on pen testing, was focused and no longer does it, or wants to get into it. I think what we need to do is wait for the messaging on the website or a specific post/page that talks about pen testing, what is offered, and explains how to sign up for it is available and is reachable. And then we can link to that in tis PR and merge this in.

Unfortunately until then, we can't add this to list as it will create confusion rather than dissolving it.

**Pull request closed without merging**
